sudo: required
dist: trusty
language: node_js
git:
  depth: 3
branches:
  only:
  - master
cache:
  directories:
  - node_modules
node_js:
- '6.4'
addons: 
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build -prod
- ls
script: karma start karma.conf.js --single-run
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: scetchtv
  endpoint: scetchtv.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  detect_encoding: true
  on:
    branch: master
  slack:
    secure: ljdqHU21J996v0EvT3j+qfk8kkIOrjUKbiZvyXQAhEa+xXf60pbIyaEUL5G4K8rpNcvmmC6o8mmT7uiwbLDh4PNexgFpFZy/3mnIiHpP1vZK6Ns3+HYCCZmYHyI9zG8emAPjL5T3nLDthY/7w0Z9TOhFPXCAjzuZyCbCRTs4789o4mmaOeuGHAnDabarvTQLw892PBfN2yL1lFSoqhdtEI8EiUkGU8sGGMPyuO1LckB14P1ee/svUsmrfPqoW26FoVLR2LYlZ6l9QNbUCp4MPbv7+9Gopdb5kWlz3vuk+AlIg+grZchUjb2p0IMgblkRE0EDFoS834ut7ygbWnmy2hra7uNYndsFd80IeifWr8MFf9/qphl/YoUIcRQT4koruBxAc86HkRJC9nO/tqHa8gCafPAuRMrf7KOlg7vA2332gpnj/FWeqBTPfunCr1/N3JPedgkiGsU5AZLhgw+7CqV/9pP2KZqrudaF59NEig08qAQJXMTzejHCbGu+3z3TWelwGUOXSOpeuDHLzzgeK/SfBW56jap6fOiVBRIQoZwG6Lgoh21afebEqo4TBLGtQ6eL4Uf15veQ9G3BDne+n1Rt7rpLlgpd9wEX3YTKupkeCp9nGRrJPIJnC1j4Zn2+pDJOUC1I7BHVcaw8/4wPSVaDlDXbblUUdUuNWBdyUIQ=
    on_success: change
    on_failure: change
  email:
    on_failure: always
notifications:
  slack:
    secure: YN7gcIxxE/+Z04wFAZ9yzYiFfW/OUwigncL41XhdAvy7k8iTM+vtRb+4q/WzdPEuUXvPJPg8vkuLpN6rYq1dfsqqk3IJZjhinsF6UAIIEXpOGKMKj4FaO0sNsc50dpYQiAEF1k6gZAN5Hmxoxh9ZQXm7GU92uTROC4W5YX4kvwttajan/aVQpTKBO0RxqiUhUAGYlwdFQrvTMcBSborCYrDS+NrUa+QkjXZC9vfOYCqQihsVNxCqozvyf91otnHByTK8KMKIlpkV1fbssHv8Llt6DUoExUePXMPdqxTSlNVY5WSqTB1WXS1aYW/8S0N05CyfjGbWsmq30ekStMHymqJbD3VJIOzmYnWlMGN/Zr0UXbBJpF0rnc1qrCRxWVLBBzekGc0nl820Qed5SYiuNovG9syRWumVkNpE9C3vsluPpzIozU3snRMEk+5j2FZmWK/3bqT02t1A7PYjiGMDp877gOAdjSGRsEhIRFK/QTdY6hDzfyUo6IntlqT948xWxs9SnlRfxEnyeFEZQzaLkgVoXCPsc/fu60r3nCh8IzXdSPYLke6F3eFnPNp/CHN7Z+vQ+a+4kYBm26Qeh/Ov5rACK1/6og6+kmBIyD9EIDHHAVy6WheDw9I6IKybRLmluP4uwpQW4rPpk+3+eSWwiIWANCNTSA4m++WPQefda9Y=
